### ISSUE TITLE
Large responses from Get-IBObject may throw JSON deserialization error

### ISSUE THREAD

**Issue by fkroessbacher** [rmbolger/Posh-IBWAPI#26]
If i request all networks with extra attributes in our Infoblox the response get’s to big for the Convert-to-JsonMethod.

Maybe u can implement something like this

https://social.technet.microsoft.com/Forums/windowsserver/en-US/833c99c1-d8eb-400d-bf58-38f7265b4b0e/error-when-converting-from-json?forum=winserverpowershell&prof=required

to get this working on big requests

**Comment by rmbolger** [comment]
Nice find. I'm actually using `Invoke-RestMethod` rather than `Invoke-WebRequest` under the hood. I had no clue there was an upper bound on the response size that they could deserialize though.  And if I can avoid it, I'd rather not have to re-write and do all the response parsing manually.

I'm wondering if I can work around this by making the paging size configurable in `Get-IBObject`. By default, it's attempting to retrieve 1000 records at a time because that's the limit the API imposes. But if you were able to tell it to only get 100 record chunks (or whatever size), you could probably avoid the internal size limit with `ConvertTo-Json` and still avoid having to do the paging yourself.

Let me see what I can do.

**Comment by fkroessbacher** [comment]
Hy

thnxs for your quick reply, i think i can try the paging in our case for u, maybe i can help u to find the best workaround. So i u need some Test on our cide in our environment i can donut for u

--
Florian Krößbacher
florian.kroessbacher@gmail.com


Am 23. Apr. 2018, 18:17 +0200 schrieb Ryan Bolger <notifications@github.com>:

**Comment by rmbolger** [comment]
I just pushed some changes to the master branch. There's now a `-PageSize` parameter for `Get-IBObject`. Can you download it and play around with lower numbers like 100-500 and see if that fixes the problem. You can also use the `-Verbose`  parameter to see what's happening under the hood.

**Comment by fkroessbacher** [comment]
Hy,

I've testet the new option -PageSize an i think it's working as u aspected. I need to PageSize 300 in our Environment to get not as Big Reponse that couldn't be parsed by Convert-to-JsonMethod

**Comment by rmbolger** [comment]
Great! Thanks for testing that. I'll make an official release with the `-PageSize` change soon.

**Comment by rmbolger** [comment]
Resolved in version 1.4
