### ISSUE TITLE
Error occurs whenusing "csv_import" function with send-file

### ISSUE THREAD

**Issue by demdante** [rmbolger/Posh-IBWAPI#55]
Very strange issue.  I have used the Send-file function to run two separate fileop functions, one which completed successfully (uploadcertificate), and one which did not complete successfully (csv_import).  I say it is strange because, one would think that the all uploads performed using send-file would fail regardless of the fileop function passed to it, but, when I run send-file and specify "csv_import" as the functionname parameter, I get the below error

![infomodule](https://user-images.githubusercontent.com/64720591/122997676-c39a6800-d39b-11eb-9092-0beade38ed5e.png)

The good news is I have already found and corrected the problem.  This issue is simply to associate the merge request I will soon create to merge the fix.

**Comment by rmbolger** [comment]
Hey @demdante. Thanks for posting the issue! This is definitely a bug, but I don't think the fix is quite right. [Property-based access](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-5.1#property-based-access) on hashtables should work just fine for adding new key/value pairs to an existing hashtable.

I think the problem in this specific instance is that the hashtable it's trying to add the key/value pair to doesn't exist. Since `$FunctionArgs` is an optional parameter, it won't always exist within the function. Check out this really minimal example:

```powershell
function TestDot { [CmdletBinding()] param([hashtable]$h) $h.foo = 'asdf'; Write-Host ($h | ConvertTo-Json) }
TestDot @{foo=1234}
TestDot @{bar='qwer'}
TestDot @{}
TestDot
```

The first three calls to TestDot work because a hashtable is passed in (even an empty one). But the last call fails with the same PropertyNotFound exception because it's effectively trying to find the `foo` property on `$null`.

I think we should be able to just add a quick null check in the `Begin{}` section and initialize the hashtable if it doesn't already exist. Something like:

```powershell
# create an empty function args hashtable if it doesn't already exist
if (-not $FunctionArgs) {
    $FunctionArgs = @{}
}
```

**Comment by rmbolger** [comment]
I’m not at a computer at the moment to test this, but the thought also occurred to me that instead of the explicit null check, we could probably just set a default value for the `$FunctionArgs` param as an empty hashtable.

**Comment by demdante** [comment]
@rmbolger You were right as far as the need for the hashtable needing to be instantiated in order to add the token key pair value.  However, these changes have already been made and are part of a pull request that is pending your approval.  You just need to approve it.

**Comment by rmbolger** [comment]
The fix is now in the main branch. I'll try to release a new version soon.
